### ISSUE TITLE
Performance. 

### ISSUE THREAD

**Issue by zek0** [randomsean/RS9000#6]
Hello. Thanks for great script but in future will be any performance tweak?

![900](https://user-images.githubusercontent.com/6064653/62150405-5c8ee880-b317-11e9-9cdd-d7f17d83ea77.jpg)

**Comment by randomsean** [comment]
Are you referring to the CPU time or memory usage?

Most of the memory consumption comes from the NUI runtime itself (which we have little control over). However, if you notice any changes in performance when performing any function of the radar, it would be worth taking a look at.

**Comment by zek0** [comment]
CPU time is very inconsistent. It will be ok is not over 0.10. Thank you!

**Comment by WolfKnight98** [comment]
I know this comment is well after the original comment date, @zek0 I'd just like to say that due to the architecture of how this radar system, and other (future) systems work, they will most likely always have a fair msec time. This is mainly due to the constant polling of the antenna system, which can't be changed too much or the radar would work inefficiently.
